amazon:
  aws:
    accesskey: test1
    secretkey: test1
  dynamodb:
    endpoint: arn:aws:dynamodb:us-east-1:448039646851
logging:
  level:
    org:
      springframework: INFO
management:
  security:
    role: SUPERUSER
security:
  user:
    name: admin1
    password: secret1
server:
  port: 8080
